name = "chroniclesync-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

routes = [
  { pattern = "api.chroniclesync.xyz", custom_domain = true }
]

[[d1_databases]]
binding = "DB"
database_name = "sync_db"
database_id = "your-d1-database-id"

[[r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage"