name = "chroniclesync-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.chroniclesync.xyz", custom_domain = true }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "sync_db"
database_id = "your-d1-database-id"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage"

[env.staging]
name = "chroniclesync-worker-staging"
routes = [
  { pattern = "api-staging.chroniclesync.xyz", custom_domain = true }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "sync_db_staging"
database_id = "your-staging-d1-database-id"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage-staging"