name = "chroniclesync-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.chroniclesync.xyz", custom_domain = true }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "sync_db"
database_id = "your-d1-database-id"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage"

[env.staging]
name = "chroniclesync-worker-staging"
zone_id = "ef68ebac5221773b48c1e308c7f599ac"
routes = [
  { pattern = "api-staging.chroniclesync.xyz", custom_domain = true }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "sync_db_staging"
database_id = "7cfdcb13-18ba-4a6d-85c3-0c75466debfc"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage-staging"