name = "chroniclesync-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"
[observability.logs]
enabled = true

[env.production]
routes = [
  { pattern = "api.chroniclesync.xyz", custom_domain = true }
]


[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage"

[env.staging]
name = "chroniclesync-worker-staging"
routes = [
  { pattern = "api-staging.chroniclesync.xyz", custom_domain = true }
]

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage-staging"
