name = "chroniclesync-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "api.chroniclesync.xyz", custom_domain = true }
]

[[env.production.d1_databases]]
binding = "DB"
database_name = "production"
database_id = "2249bfac71db40ad8b7de370021d14fc"

[[env.production.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage"

[env.staging]
name = "chroniclesync-worker-staging"
zone_id = "ef68ebac5221773b48c1e308c7f599ac"
routes = [
  { pattern = "api-staging.chroniclesync.xyz", custom_domain = true }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "staging"
database_id = "3eb2f396c7e749d7a993ce86d90875b2"

[[env.staging.r2_buckets]]
binding = "STORAGE"
bucket_name = "sync-storage-staging"